name: Build Documentation

on: [pull_request, push]

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 14
    - run: chmod +x gradlew
    - run: ./gradlew javadoc
    - uses: actions/upload-artifact@v2
      with:
        path: build/docs/javadoc
